services:
  - type: web
    name: mediconnect-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false # You'll need to set this in the Render dashboard
      - key: JWT_SECRET
        sync: false # You'll need to set this in the Render dashboard
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        sync: false # Set this to your Vercel frontend URL
    plan: free 